### PR TITLE
Selected text support

### PR DESCRIPTION
**Pull request by junichi11**
If you prefer to get text from document, you may also like this feature.
If text is selected, plugin outputs only there.

Please feel free to reject this feature if you don't like it ;)

### CODE REVIEW

**Comment by madflow** [comment]
This sounds promising - Right know I am working on a better Lexer implementation. When this is finished - I will look into this pull request.

**Comment by madflow** [comment]
I really like the idea. I testes the functionality - and it works as expected. 

In my opinion though - this selected text HTML Export should only apply to user actions, when the user does a right-click on the selected text and select the options from the popup menu. Like the "View Selected Source" feature in the Firefox Web Browser.

Otherwise this could be confusing and could lead to unexpected export results.

**Comment by junichi11** [comment]
IMHO, I think that "text is selected" means that user expects that there is exported. We should write that into README file because user might use the editor toolbar button. 

In case of NB other action example - `copy` i.e. `Ctrl + C` : If we select text, it's copied. But if we don't select anything, line with caret is copied.

**Comment by madflow** [comment]
I could live with selected text and the editor-toolbar. When you open a file and select something - and then right-click on this file in the project-tree - then you will also only export the selected text. I cannot see how someone would expect this ;) Can this be changed easily?

**Comment by junichi11** [comment]
I see now what you want to say :+1: 

> Can this be changed easily?

If this means that action name is changed (View Html -> View Html (selected text)) when text is selected,
Maybe, I can change it. It needs some changes (e.g. we have to change ActionListener to other class, implement Presenter class). But I wonder if we have to change them. I think that it is no problem if  there is a explanation for it in README file. 

In other idea, show confirmation dialog if text is selected. But this might be annoying for user.

**Comment by madflow** [comment]
I am closing this pull request for now because I am not fully convinced how useful this might be - Let's keep this in mind for future versions ;)

**Pull request closed without merging**
