### PR TITLE
Use annotation-based registrations

### PR DESCRIPTION
**Pull request by stengerh**
This PR moves several registrations from the layer file to annotations. It was inspired by #122 but addresses more than just the MIME type resolver.

### CODE REVIEW

**Comment by madflow** [comment]
Is this ready to be merged?

**Comment by stengerh** [comment]
Sorry for the late reply. Yes, it is. I am a fan of code reviews so I did not want to merge it myself. ;)

**Comment by madflow** [comment]
👍

**Comment by Chris2011** [comment]
What about a new release for this please?

**Comment by madflow** [comment]
@Chris2011 I can prepare a test release in the next few days.

**Comment by Chris2011** [comment]
Great, thx :)

**Comment by madflow** [comment]
I tagged 2.3.2 and drafted a new release. I compiled the plugin in a Netbeans 8.1 environment - it should work with 8.2, too. I just did a "quick" test.

**Pull request merged**
