### PR TITLE
Add typinghooks

### PR DESCRIPTION
**Pull request by junichi11**
nb-md-typinghook-o

### CODE REVIEW

**Comment by madflow** [comment]
Could you add some unit tests?

**Comment by madflow** [comment]
@junichi11 

I can see that is is a useful feature - but I would personally not use it.

From a user perspective - I would not want to have consecutive Headers when I press enter. Also - this will not allow me to just enter a list operator (*,-) and not text - it will delete it at the moment. The plus (+) sign does not work at the moment.

So here is something "forced" on me - which will break the editor that I like (and others?)

From a programmer perspective - I really would like some (unit, functional) tests with this - so the Regular Expressions are tested thoroughly. But since we are not developing software for nuclear reactors I would let this slide :D

I would agree to merge this, if we can make this configurable under "Options". This way I can have the editor that I like and others can have the cool typing hooks. What do you think?

**Comment by azige** [comment]
The MarkdownPad 2 has the function like this while it's only for the list operators (*, -, +), not for headers.
I agreed with @madflow . There should be options to set which operators should apply this function.

**Comment by stengerh** [comment]
I agree about restricting this function to lists and maybe block quotes (>). This would reflect what users know from word processors in popular office software suites.

**Comment by junichi11** [comment]
@madflow 

> Could you add some unit tests?

Of course, I would like to add some unit tests (should add them).  But I don't know how to test this feature correctly yet. Generally, It seems that CslTestBase class is used in official modules. But I was not able to use it. I'm not sure that cause...

> I would not want to have consecutive Headers when I press enter. 
>  The plus (+) sign does not work at the moment.

If header is unnecessary, I'll remove it. 
Actually, I wanted to add `#` when we press `shift + enter`. But I implemented like this because I don't know that way. Instead, we can disable it when we press `shift + enter`.
Currently, `#` is removed and caret position is moved next line if we press enter when a line has only `#`. I'll add some settings to Options. e.g. enabled, header, lists(*, -, +) and >. 

> Also - this will not allow me to just enter a list operator (*,-) and not text - it will delete it at the moment.

What does this mean?

**Comment by madflow** [comment]
> I'll add some settings to Options. e.g. enabled, header, lists(*, -, +) and >. 

My proposal would also be an on/off switch for the complete feature.

> What does this mean?

Sorry - This was an example of the editor taking over my typing.

When I enter "`*`" with no text following afterwards - and then press enter - then the editor automatically deletes the "`*`" ;) This is something I personally would not need.

**Comment by junichi11** [comment]
> My proposal would also be an on/off switch for the complete feature.

If this means the code template feature, I think that it is impossible probably.

> When I enter "_" with no text following afterwards - and then press enter - then the editor automatically deletes the "_" ;) This is something I personally would not need.

Thanks for your answer :) IMHO, I think that it is general behavior. If we don't want to delete it, we can avoid that with pressing `Shift + Enter`. Is there anyone that has a opinion? If many users not need that, I'll fix that.

**Comment by madflow** [comment]
> If this means the code template feature, I think that it is impossible probably.

I am reffering to the above pull requests - not code templates ;)

**Comment by madflow** [comment]
Cleaning up a little bit here - so I will close this specific pull request. Feel free to re-open it or create a new one with the suggestions we had.

**Comment by markiewb** [comment]
@junichi11 : Will you provide an updated pull request ("with the suggestions we had"), so that this neat feature can be merged?

**Comment by junichi11** [comment]
Of course, I'll update it. Please wait a while.
Thanks.

**Comment by junichi11** [comment]
nb-md-typinghooks-options
- auto addition for lists and block quates operator (Add operators(*, -, +, >) when new line is inserted)
- remove empty list (If list is empty, it's removed when new line is inserted)
- reorder ordered list number (Reorder ordered list number when number is added/removed)
- remove ordered list number (Number is also removed when white space is removed)

() is tool tip text.

I'll add above options. If my English is wrong, please let me know.

Thanks.

**Comment by junichi11** [comment]
I've added some improvements (e.g. remove suggestion for header `#`, add options).
Could you try to check it?
If you prefer to be sent a pull request as one commit, I'll close this issue and send a new pull request again.

Thanks.

**Comment by stengerh** [comment]
Some things I noticed on the screenshot of the options panel:
- "block _quates_ operator" should be "block _quotes_ operator"
- Check box labels usually have the first word capitalized, e.g. "Auto addition..." instead of "auto addition..."

Please ignore this comment if these are already changed in the latest patch. ;)

**Comment by junichi11** [comment]
@stengerh 
Thanks for your confirmation! I'll fix it ;)

**Comment by madflow** [comment]
I merged it into the master branch. Let's test! :D

**Pull request merged**
