### PR TITLE
Fix an encoding problem for running ViewHtmlAction

### PR DESCRIPTION
**Pull request by junichi11**
- Add null checking for FileObject
- Check encoding for FileObject if ViewHtmlOnSave is enabled

### CODE REVIEW

**Comment by junichi11** [comment]
This is patch for issue #20

**Comment by madflow** [comment]
@junichi11 Maybe I merged this prematurely... 

There is a log file in the root directory - which we can simply remove of course.

But now there is a regression in MarkdownViewHtmlAction.java. Whenever the user clicks on View HTML only the already saved content is displayed. This behavior was the default before we introduced "View HTML On Save".

Was this necessary to fix the encoding issue? As far as I can tell - if I delete the check:

```
markdownOptions.isViewHtmlOnSave()
```

the feature works equally well. Was this check really neccessary?

**Comment by junichi11** [comment]
> There is a log file in the root directory - which we can simply remove of course.

Ohh... I'm so sorry. I did not notice it...
Please remove it.

> But now there is a regression in MarkdownViewHtmlAction.java. Whenever the user clicks on View HTML only the already saved content is displayed. This behavior was the default before we introduced "View HTML On Save".

I was just returned to the previous state. because this issue was occurred when I added the onSave feature.
So if you prefer to use document text, please remove the checking isViewHtmlOnsave ;)

Thanks.

**Comment by madflow** [comment]
Thank you for the clarification. For the time being I reverted it back to the previous state - so we do not introduce a regression when we are actually trying to fix something else. Thanks again!

**Pull request merged**
