### PR TITLE
Support for View Html on save

### PR DESCRIPTION
**Pull request by junichi11**
I have added `On Save` settings to Option.
netbeans-markdown-run-on-save

If you don't like this, please feel free to reject this.

### CODE REVIEW

**Comment by madflow** [comment]
I reckon this would be useful if you have configured the embedded browser as preview. For anyone else - this would be very annoying - wouldn't it be?

Can you elaborate what the changes in `src/flow/netbeans/markdown/MarkdownViewHtmlAction.java` are for?

**Comment by junichi11** [comment]
> I reckon this would be useful if you have configured the embedded browser as preview. For anyone else - this would be very annoying - wouldn't it be?

Yes, it is for the embedded browser. If user doesn't use embedded browser, new tabs will be created.
But I think that it is the same as if user run ViewHtml action again. User can uncheck this option simply.

> Can you elaborate what the changes in src/flow/netbeans/markdown/MarkdownViewHtmlAction.java are for?

File is not saved yet when OnSaveTask is run. So, I get the contents from document.
(In other way, we have to add FileChangeListener to file object.)
We can guess that action is run on file node if document object is null.

Thanks.

**Comment by madflow** [comment]
I merged the pull request. Thank you! A side effect is - that the document does not have to saved to preview it anymore. LIKE!

I renamed the pane to "Miscellaneous" - because then we can have multiple new options there.

**Comment by junichi11** [comment]
I see. Thank you :smile:

**Pull request merged**
