### PR TITLE
Dependencies update for NetBeans 8.1 compile & run

### PR DESCRIPTION
**Pull request by le-yams**
Hi guys,

I updated the dependencies in order to compile & run the plugin under NB 8.1 (related to #94  and #103).
It seems to work fine with the following environments (java 1.8.0_66):
- Product Version = NetBeans IDE 8.1 (Build 201510222201) (#bb5d68d8a020)
  - Operating System = Windows 7 version 6.1 running on amd64
  - Operating System = Linux version 3.13.0-24-generic running on amd64

(It includes a small static import conflict fix by stengerh).

Best regards,
Yann

### CODE REVIEW

**Comment by madflow** [comment]
Thanks for this - I did a quick check and the plugin installs and compiles fine with this PR (Ubuntu ). I can compile a pre-release for testing when I have the "signing" of the plugin back in order.

**Comment by madflow** [comment]
I just compiled a npm with the changes in NetBeans 8.1

https://github.com/madflow/flow-netbeans-markdown/releases/tag/2.3.1-preview

I would appreciate a test and feedback from any one interested. Thanks.

**Comment by gonssal** [comment]
Tested the release you linked with 8.1 under Linux, seems to work fine.

**Comment by le-yams** [comment]
Seems to work fine with:
- **Product Version:** NetBeans IDE 8.1 (Build 201510222201)
- **Java:** 1.8.0_66; Java HotSpot(TM) 64-Bit Server VM 25.66-b17
- **System:** Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)

Regards,
Yann

**Pull request merged**
