### PR TITLE
NetBeans 8 port of JavaFX based preview

### PR DESCRIPTION
**Pull request by stengerh**
This is the same as my previous experimental version of the JavaFX based preview. Thanks to new features in NetBeans IDE 8 it no longer requires custom extensions to the build script or class loader magic. Due to the same reason it also should no longer conflict with other JavaFX enabled plugins.

**Requirements**
This version of the plugin requires NetBeans IDE 8 and JDK 7 with bundled JavaFX 2.2 or JDK 8. Strictly speaking it should work with a JRE but (parts of) the IDE itself require a JDK.

I have uploaded a [pre-release](https://github.com/stengerh/flow-netbeans-markdown/releases/tag/v1.6.0-experimental) for evaluation.

### CODE REVIEW

**Comment by junichi11** [comment]
:+1:

**Comment by junichi11** [comment]
I think that we should create new branches if we can't use these changes in NetBeans 7.4. e.g. nb80, nb74, ...

**Comment by stengerh** [comment]
Another approach would be to create a module suite for Markdown support and split the NB8 specific functionality into a separate module. Still, separate branches will probably be easier to maintain.

**Comment by madflow** [comment]
It could be cumbersome to maintain two (pseudo-)stable branches though. I always update NetBeans when there is a new release - since I only use it at work for PHP. But I believe there are some users who hesitate longer or cannot update -  because they rely on a much larger plugin stack than our little md plugin.

I cannot comment on a the module suite really - because I know to little how this would play out.

So lets try branching nb8 and look where it goes from there?

**Comment by madflow** [comment]
I created a new branch nb8 and merged the pull request manually. I cannot test this easily - since I do not have the needed setup available. 

I had to rewrite the options form (MarkdownPanel.form) how I thought it would look like. Comparing these diffs was a monkeys task and NetBeans does not allow to edit these auto-generated code lines.

The recent pull requests and small fixes are incorporated in this merge. Hopefully I  did not break more things than did good ;)

**Pull request closed without merging**
